### ISSUE TITLE
DBFace 480x640 models don't work

### ISSUE THREAD

**Issue by m0ka-Lv98** [PINTO0309/PINTO_model_zoo#110]
Hi, thanks for your interesting works!
I tried to run 041_DBFace/dbface_infer_tflite.py using dbface_keras_480x640_integer_quant_nhwc.tflite and also other 480x640 models, but they created wrong boxes. Other models, like dbface_keras_256x256_integer_quant_nhwc.tflite, detected in a right way. Could you create 480x640 models correctly?
And it seems there are bugs in dbface_infer_tflite.py so I also created PR. Please check it out!

**Comment by PINTO0309** [comment]
Just today, I was re-transforming the model using the new workflow. Please wait a moment.

**Comment by m0ka-Lv98** [comment]
Great! I will wait for it!

**Comment by PINTO0309** [comment]
I've just committed MobileNetV3's DBCFace, which I started working on before I got the issue. Can you confirm that it works? I will start working on MobileNetV2.
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/041_DBFace/20_mobilenetv3

**Comment by m0ka-Lv98** [comment]
I tried model_float16_quant.tflite, model_float32_quant.tflite, model_integer_quant.tflite in saved_model_480x640, but it didn't detect face...

**Comment by PINTO0309** [comment]
Here's the result of reasoning with my face; it looks like I'm getting the correct information for the four points in the Box, but the scale and stride values required may be different than in MobileNetV2. I expect that it probably doesn't work well with the sample code that I committed a year ago. I guess I need to carefully understand again the inference logic of the quoted PyTorch.
https://github.com/dlunion/DBFace/blob/master/main.py

model_float32.tflite
Box: (1, 80, 80, 4)
```
array([[[[2.0248861, 2.3030493, 2.154567 , 2.408706 ],
         [1.9582167, 2.248324 , 2.0772004, 2.3320637],
         [1.8201137, 2.1086886, 1.9672185, 2.2242632],
         ...,
         [1.8265394, 2.117771 , 1.9751486, 2.2308533],
         [1.9271259, 2.2495885, 2.056237 , 2.3391829],
         [2.0229752, 2.313377 , 2.1739268, 2.4141083]],

        [[1.9987401, 2.271855 , 2.0597296, 2.2783   ],
         [1.9153229, 2.2063313, 2.01699  , 2.2490854],
         [1.7903852, 2.0820992, 1.9218525, 2.156876 ],
         ...,
         [1.7958573, 2.088791 , 1.9274783, 2.1619096],
         [1.8558884, 2.1903427, 1.9901466, 2.2196698],
         [1.9937885, 2.277318 , 2.0925097, 2.3037493]],

        [[1.8728375, 2.1348886, 1.9788703, 2.2312305],
         [1.8232738, 2.0973597, 1.9457675, 2.2058954],
         [1.7453516, 2.0244365, 1.8896371, 2.1442943],
         ...,
         [1.7460018, 2.0272715, 1.8927548, 2.1466265],
         [1.7878835, 2.0879776, 1.9304523, 2.1889846],
         [1.8670957, 2.1466548, 1.9982641, 2.2391403]],

        ...,

        [[1.8716143, 2.1340914, 1.9777942, 2.2304904],
         [1.822361 , 2.096147 , 1.9450847, 2.2054644],
         [1.7445891, 2.023379 , 1.8888887, 2.1441104],
         ...,
         [1.7467049, 2.0289261, 1.8945904, 2.1484714],
         [1.7866898, 2.0857344, 1.9289687, 2.188177 ],
         [1.8620994, 2.1453762, 1.9995236, 2.2386465]],

        [[2.1104982, 2.3457909, 2.1576383, 2.3931084],
         [2.0346043, 2.3100011, 2.0773327, 2.3704736],
         [1.8463463, 2.14687  , 1.9691682, 2.236719 ],
         ...,
         [1.8512471, 2.1568608, 1.9777472, 2.2438357],
         [1.9480413, 2.2924938, 2.0643518, 2.3326783],
         [2.0575874, 2.315434 , 2.1416063, 2.395898 ]],

        [[2.0075874, 2.2987452, 2.1439605, 2.3973546],
         [1.9433864, 2.2510233, 2.0828416, 2.3380406],
         [1.8298   , 2.1223195, 1.9786003, 2.237702 ],
         ...,
         [1.8369203, 2.131104 , 1.9882952, 2.245886 ],
         [1.9044528, 2.2350261, 2.036747 , 2.3276153],
         [1.9819492, 2.281123 , 2.1332812, 2.3731568]]]], dtype=float32)
```

**Comment by PINTO0309** [comment]
Sorry, I must have made a mistake in converting ReLU6. Redo the conversion. I'm really sorry.

https://pytorch.org/docs/stable/generated/torch.nn.functional.relu6.html#torch.nn.functional.relu6

NG: torch.clamp(torch.clamp(x, min=torch.tensor(0)), max=torch.tensor(6)) / 6
OK: torch.clamp(torch.clamp(x, max=torch.tensor(0)), min=torch.tensor(6)) / 6

**Comment by PINTO0309** [comment]
Furthermore, I made a mistake in converting HardSigmoid to HardSwish. Also, there was a lack of normalization process just before making inferences.
![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/33194443/123299829-de640c80-d554-11eb-81ad-4d98fd555e72.gif)

- MobileNetV3 + DBFace
```python
mean = [0.408, 0.447, 0.47]
std = [0.289, 0.274, 0.278]
img = ((img / 255.0 - mean) / std).astype(np.float32)
```

**Comment by PINTO0309** [comment]
Committed again.
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/041_DBFace/20_mobilenetv3

**Comment by m0ka-Lv98** [comment]
I tried some of them. Results were like here.

- float16_quant.tflite
  - 320x320
  Recall is low but I think this detects faces in a right way
![saved_model_320x320_model_float16_quant tflite](https://user-images.githubusercontent.com/53432675/123356875-81437780-d5a3-11eb-8f1e-9882aa3babe1.jpg)

  - 480x640
  This model failed to detect
![saved_model_480x640_model_float16_quant tflite](https://user-images.githubusercontent.com/53432675/123356891-8accdf80-d5a3-11eb-81fb-b126f4ae299b.jpg)

  - 640x960
  This one got an error.
    ```Traceback (most recent call last):
    File "dbface_infer_tflite.py", line 216, in <module>
      main(args)
    File "dbface_infer_tflite.py", line 182, in main
      objs = detect(hm=hm, box=box, landmark=lm, threshold=0.4, nms_iou=0.5)
    File "dbface_infer_tflite.py", line 100, in detect
      x, y, r, b = box[cy, cx, :]
    IndexError: index 716 is out of bounds for axis 0 with size 160 
  - 800x1280
  The same error as above.

- integer_quant.tflite
  - 320x320
    ```Traceback (most recent call last):
    File "dbface_infer_tflite.py", line 216, in <module>
      main(args)
    File "dbface_infer_tflite.py", line 182, in main
      objs = detect(hm=hm, box=box, landmark=lm, threshold=0.4, nms_iou=0.5)
    File "dbface_infer_tflite.py", line 100, in detect
      x, y, r, b = box[cy, cx, :]
    ValueError: not enough values to unpack (expected 4, got 1)
  - 480x640
    ```Traceback (most recent call last):
    File "dbface_infer_tflite.py", line 216, in <module>
      main(args)
    File "dbface_infer_tflite.py", line 182, in main
      objs = detect(hm=hm, box=box, landmark=lm, threshold=0.4, nms_iou=0.5)
    File "dbface_infer_tflite.py", line 100, in detect
      x, y, r, b = box[cy, cx, :]
    IndexError: index 1598 is out of bounds for axis 0 with size 120
  - 640x960, 800x1280
  The same error as 480x640.

**Comment by PINTO0309** [comment]
Ignore the old sample programs that have been committed. Also, the model has been updated, so please download it again. Since the normalization process is embedded in the model, there is no need for the normalization process in the program. I'm using PyTorch's layers because I'm implementing post-processing in a crude way. Feel free to modify the logic to your liking.
```python
import common
import numpy as np
import torch
import torch.nn.functional as F
import cv2
import os
from argparse import ArgumentParser
from tensorflow.lite.python.interpreter import Interpreter


def nms(objs, iou=0.5):

    if objs is None or len(objs) <= 1:
        return objs

    objs = sorted(objs, key=lambda obj: obj.score, reverse=True)
    keep = []
    flags = [0] * len(objs)
    for index, obj in enumerate(objs):

        if flags[index] != 0:
            continue

        keep.append(obj)
        for j in range(index + 1, len(objs)):
            if flags[j] == 0 and obj.iou(objs[j]) > iou:
                flags[j] = 1
    return keep


def detect(interpreter, input_blob, output_blob, image, threshold=0.4, nms_iou=0.5):

    interpreter.set_tensor(input_blob[0]['index'], image)
    interpreter.invoke()

    lm = interpreter.get_tensor(output_blob[0]['index']).transpose((0,3,1,2)) # 1,h,w,10
    box = interpreter.get_tensor(output_blob[1]['index']).transpose((0,3,1,2)) # 1,h,w,4
    hm = interpreter.get_tensor(output_blob[2]['index']).transpose((0,3,1,2)) # 1,1,h,w

    hm = torch.from_numpy(hm).clone()
    box = torch.from_numpy(box).clone()
    landmark = torch.from_numpy(lm).clone()

    hm_pool = F.max_pool2d(hm, 3, 1, 1)
    scores, indices = ((hm == hm_pool).float() * hm).view(1, -1).cpu().topk(1000)
    hm_height, hm_width = hm.shape[2:]

    scores = scores.squeeze()
    indices = indices.squeeze()
    ys = list((indices / hm_width).int().data.numpy())
    xs = list((indices % hm_width).int().data.numpy())
    scores = list(scores.data.numpy())
    box = box.cpu().squeeze().data.numpy()
    landmark = landmark.cpu().squeeze().data.numpy()

    stride = 4
    objs = []
    for cx, cy, score in zip(xs, ys, scores):
        if score < threshold:
            break

        x, y, r, b = box[:, cy, cx]
        xyrb = (np.array([cx, cy, cx, cy]) + [-x, -y, r, b]) * stride
        x5y5 = landmark[:, cy, cx]
        x5y5 = (common.exp(x5y5 * 4) + ([cx]*5 + [cy]*5)) * stride
        box_landmark = list(zip(x5y5[:5], x5y5[5:]))
        objs.append(common.BBox(0, xyrb=xyrb, score=score, landmark=box_landmark))
    return nms(objs, iou=nms_iou)


def camera_demo():
    interpreter = Interpreter(model_path='model_float32.tflite', num_threads=4)
    interpreter.allocate_tensors()
    input_blob = interpreter.get_input_details()
    output_blob = interpreter.get_output_details()

    cap = cv2.VideoCapture(0)
    cap.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)

    while True:
        ok, frame = cap.read()
        if not ok:
            continue
        img = cv2.resize(frame, (640,480))
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img = img.astype(np.float32)
        img = img[np.newaxis, :, :, :]
        objs = detect(interpreter, input_blob, output_blob, img)

        for obj in objs:
            common.drawbbox(frame, obj)

        cv2.imshow("demo DBFace", frame)
        key = cv2.waitKey(1) & 0xFF
        if key == ord('q'):
            break

    cap.release()
    cv2.destroyAllWindows()

if __name__ == "__main__":
    camera_demo()
```
https://user-images.githubusercontent.com/33194443/123439876-26df0100-d60d-11eb-85e5-c5f85b9b1490.mp4

**Comment by m0ka-Lv98** [comment]
Thank you! I finally got right result (This is the result for `mobilenet_v3 640x960 integer_quant.tflite`).

![output](https://user-images.githubusercontent.com/53432675/123465407-0f157600-d629-11eb-970f-ccd87d40f2f5.jpg)

But there still seems to be some problems in other models.
Using `saved_model_480x640/model_integer_quant.tflite` caused an error below.
```
Traceback (most recent call last):
  File "dbface_infer_tflite.py", line 150, in <module>
    detect_from_image()
  File "dbface_infer_tflite.py", line 141, in detect_from_image
    objs = detect(interpreter, input_blob, output_blob, img)
  File "dbface_infer_tflite.py", line 68, in detect
    scores, indices = ((hm == hm_pool).float() * hm).view(1, -1).cpu().topk(1000)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
```
I printed hm.shape, which is expected to be (1, 1, 120, 160), but it was (1, 10, 120, 160), which is the shape of lm. I think this is caused by index mismatches. The modified implementation below is messy but this detected faces correctly, so there may be some mistakes during converting models.
```
x = torch.from_numpy(hm).clone()
y = torch.from_numpy(box).clone()
z = torch.from_numpy(lm).clone()
for var in [x, y, z]:
    if var.shape[1]==1:
        hm = var
    elif var.shape[1]==4:
        box = var
    elif var.shape[1]==10:
        landmark = var
```

**Comment by PINTO0309** [comment]
Thanks for pointing that out. It is within my expectation that the problem will occur. The process by which TensorFlow transforms a model changes the order of the output irregularly. I'm aware of it. But I just haven't dealt with it because it's a pain. With a little time, I can fix it. 

I'll respond when I'm motivated.

**Comment by m0ka-Lv98** [comment]
Okay, I got it. Thanks for converting these models!

**Comment by PINTO0309** [comment]
The proposal was incorporated. a27919fc63a9f1602e3630e645ef6015e25248fc
