### ISSUE TITLE
LSTR conversion problem

### ISSUE THREAD

**Issue by Hank880223** [PINTO0309/PINTO_model_zoo#258]
### Issue Type

Bug

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

PyTorch, ONNX

### Model name and Weights/Checkpoints URL

https://github.com/liuruijin17/LSTR

### Description

Hello
I can't convert pytorch model to onnx model using the docker environment you provided.
When converting the model, the following logs appear. It seems to be a problem with the torch version, do you know how to solve it?

Thank you !

### Relevant Log Output

```shell
user@hank:~/workdir/LSTR-main$ python test.py LSTR --testiter 500000 --modality images --image_root ./ --debug
cfg_file: ./config/LSTR.json
loading all datasets...
split: val
loading parameters at iteration: 500000
building neural network...
/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:122: UserWarning: 
    Found GPU0 NVIDIA GeForce RTX 2080 which is of cuda capability 7.5.
    PyTorch no longer supports this GPU because it is too old.
    The minimum cuda capability supported by this library is 8.6.
    
  warnings.warn(old_gpu_warn % (d, name, major, minor, min_arch // 10, min_arch % 10))
/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:145: UserWarning: 
NVIDIA GeForce RTX 2080 with CUDA capability sm_75 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_86.
If you want to use the NVIDIA GeForce RTX 2080 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Total parameters: 765754
Traceback (most recent call last):
  File "test.py", line 150, in <module>
    test(testing_db,
  File "test.py", line 65, in test
    nnet = NetworkFactory()
  File "/home/user/workdir/LSTR-main/nnet/py_factory.py", line 67, in __init__
    macs, params, = profile(self.model, inputs=(input_test, input_mask), verbose=False)
  File "/home/user/.local/lib/python3.8/site-packages/thop/profile.py", line 188, in profile
    model(*inputs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1129, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/workdir/LSTR-main/nnet/py_factory.py", line 39, in forward
    return self.module(*xs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1129, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/workdir/LSTR-main/models/py_utils/kp.py", line 213, in forward
    return self._test(*xs, **kwargs)
  File "/home/user/workdir/LSTR-main/models/py_utils/kp.py", line 208, in _test
    return self._train(*xs, **kwargs)
  File "/home/user/workdir/LSTR-main/models/py_utils/kp.py", line 186, in _train
    p = self.bn1(p)  # B 16 180 320
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1129, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/workdir/LSTR-main/models/py_utils/kp.py", line 53, in forward
    scale = w * (rv + eps).rsqrt()
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by PINTO0309** [comment]
As stated in the error message. Read the error message.
https://developer.nvidia.com/cuda-11-6-2-download-archive?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=20.04&target_type=deb_local
