### ISSUE TITLE
I try to convert intel's Handwritten Text Recognition Demo but I met a error

### ISSUE THREAD

**Issue by jprorikon** [PINTO0309/PINTO_model_zoo#340]
### Issue Type

Bug

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

TensorFlow.js

### Model name and Weights/Checkpoints URL

https://github.com/openvinotoolkit/open_model_zoo/tree/master/demos/handwritten_text_recognition_demo/python

### Description

With the latest version of openvino2tensorflow, I can not convert Handwritten-japanese-recognition-0001.xml with 
--weight_replacement_config weights_replacement.json option.

### Relevant Log Output

```shell
ERROR: Exception encountered when calling layer "tf.linalg.matmul" (type TFOpLambda).

Shape must be at least rank 2 but is rank 1 for '{{node tf.linalg.matmul/MatMul}} = BatchMatMulV2[T=DT_FLOAT, adj_x=true, adj_y=true](Placeholder, tf.linalg.matmul/MatMul/b)' with input shapes: [1,512,186], [3].

Call arguments received by layer "tf.linalg.matmul" (type TFOpLambda):
  • a=tf.Tensor(shape=(1, 512, 186), dtype=float32)
  • b=array([  1, 512, 186])
  • transpose_a=True
  • transpose_b=True
  • adjoint_a=False
  • adjoint_b=False
  • a_is_sparse=False
  • b_is_sparse=False
  • output_type=None
  • name=None
ERROR: model_path  : handwritten-japanese-recognition-0001.xml
ERROR: weights_path: handwritten-japanese-recognition-0001.bin
ERROR: layer_id    : 76
ERROR: input_layer0 layer_id=74: KerasTensor(type_spec=TensorSpec(shape=(1, 512, 186), dtype=tf.float32, name=None), name='tf.reshape/Reshape:0', description="created by layer 'tf.reshape'")
ERROR: input_layer1 layer_id=75: Const(ndarray).shape  (3,)
array([  1, 512, 186])
ERROR: The trace log is below.
Traceback (most recent call last):
  File "/home/liuzhaoyu/.local/bin/openvino2tensorflow", line 3822, in convert
    tf_layers_dict[layer_id] = tf.linalg.matmul(
  File "/home/liuzhaoyu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/liuzhaoyu/.local/lib/python3.10/site-packages/keras/layers/core/tf_op_layer.py", line 119, in handle
    return TFOpLambda(op)(*args, **kwargs)
  File "/home/liuzhaoyu/.local/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
ValueError: Exception encountered when calling layer "tf.linalg.matmul" (type TFOpLambda).

Shape must be at least rank 2 but is rank 1 for '{{node tf.linalg.matmul/MatMul}} = BatchMatMulV2[T=DT_FLOAT, adj_x=true, adj_y=true](Placeholder, tf.linalg.matmul/MatMul/b)' with input shapes: [1,512,186], [3].

Call arguments received by layer "tf.linalg.matmul" (type TFOpLambda):
  • a=tf.Tensor(shape=(1, 512, 186), dtype=float32)
  • b=array([  1, 512, 186])
  • transpose_a=True
  • transpose_b=True
  • adjoint_a=False
  • adjoint_b=False
  • a_is_sparse=False
  • b_is_sparse=False
  • output_type=None
  • name=None
ERROR: Please refer to 6-7 in the README first. https://github.com/PINTO0309/openvino2tensorflow
```

**Comment by PINTO0309** [comment]
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/055_Handwritten_Japanese_Recognition

**Comment by PINTO0309** [comment]
![image](https://github.com/PINTO0309/PINTO_model_zoo/assets/33194443/2f615ef9-3ceb-40ee-a6e2-6ea7abbbcdc2)

**Comment by PINTO0309** [comment]
![image](https://github.com/PINTO0309/PINTO_model_zoo/assets/33194443/3a8654e5-5f76-4a30-b2ca-c6df19e9e6f4)

```
onnx2tf -i model_float32.onnx -osd -coion
```
![image](https://github.com/PINTO0309/PINTO_model_zoo/assets/33194443/bb9e4c41-9a83-4428-af75-61e0b356f1dc)

```
pip install tensorflowjs

onnx2tf -i mobilenetv2-12.onnx -ois input:1,3,224,224 -osd

tensorflowjs_converter \
--input_format tf_saved_model \
--output_format tfjs_graph_model \
saved_model \
tfjs_model
```
![image](https://github.com/PINTO0309/PINTO_model_zoo/assets/33194443/fb3b472d-b1b1-4215-9d2f-4d975aa844e5)

![image](https://github.com/PINTO0309/PINTO_model_zoo/assets/33194443/7ae93702-b55e-4488-a247-2ba32c80c702)
