### ISSUE TITLE
324 UFLDv2 CurveLanes onnx convert support

### ISSUE THREAD

**Issue by Auc7us** [PINTO0309/PINTO_model_zoo#434]
### Issue Type

Support

### OS

Ubuntu

### OS architecture

x86_64

### Programming Language

Python

### Framework

ONNX

### Model name and Weights/Checkpoints URL

https://github.com/cfzd/Ultra-Fast-Lane-Detection-v2

### Description

the curve lane script provided by the authors to convert to onnx fails 
I added the following line to make it work 

```
    elif cfg.dataset == 'CurveLanes':
        cls_num_per_lane = 72

```
after line 56 in pt2onnx.py

and i get this error i shared in log

how did you get around this 
did you use your own script for conversion? can you share it? 
im a student at UW Madison and this would be really helpful
Thanks

### Relevant Log Output

```shell
(ll) auc7us@vision:~/Documents/Ultra-Fast-Lane-Detection-v2$ python deploy/pt2onnx.py --config_path configs/curvelanes_res18.py --model_path weights/curvelanes_res18.pth 
/home/auc7us/miniconda3/envs/ll/lib/python3.12/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/auc7us/miniconda3/envs/ll/lib/python3.12/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/auc7us/Documents/Ultra-Fast-Lane-Detection-v2/deploy/pt2onnx.py:64: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(args.model_path, map_location='cpu')['model']
start convert...
torch.Size([1, 20, 10, 50])
Traceback (most recent call last):
  File "/home/auc7us/Documents/Ultra-Fast-Lane-Detection-v2/deploy/pt2onnx.py", line 72, in <module>
    convert(net, args)
  File "/home/auc7us/Documents/Ultra-Fast-Lane-Detection-v2/deploy/pt2onnx.py", line 29, in convert
    torch.onnx.export(model, images,
  File "/home/auc7us/miniconda3/envs/ll/lib/python3.12/site-packages/torch/onnx/utils.py", line 551, in export
    _export(
  File "/home/auc7us/miniconda3/envs/ll/lib/python3.12/site-packages/torch/onnx/utils.py", line 1648, in _export
    graph, params_dict, torch_out = _model_to_graph(
                                    ^^^^^^^^^^^^^^^^
  File "/home/auc7us/miniconda3/envs/ll/lib/python3.12/site-packages/torch/onnx/utils.py", line 1170, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/auc7us/miniconda3/envs/ll/lib/python3.12/site-packages/torch/onnx/utils.py", line 1046, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/auc7us/miniconda3/envs/ll/lib/python3.12/site-packages/torch/onnx/utils.py", line 950, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/auc7us/miniconda3/envs/ll/lib/python3.12/site-packages/torch/jit/_trace.py", line 1497, in _get_trace_graph
    outs = ONNXTracedModule(
           ^^^^^^^^^^^^^^^^^
  File "/home/auc7us/miniconda3/envs/ll/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/auc7us/miniconda3/envs/ll/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/auc7us/miniconda3/envs/ll/lib/python3.12/site-packages/torch/jit/_trace.py", line 141, in forward
    graph, out = torch._C._create_graph_by_tracing(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/auc7us/miniconda3/envs/ll/lib/python3.12/site-packages/torch/jit/_trace.py", line 132, in wrapper
    outs.append(self.inner(*trace_inputs))
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/auc7us/miniconda3/envs/ll/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/auc7us/miniconda3/envs/ll/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/auc7us/miniconda3/envs/ll/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1543, in _slow_forward
    result = self.forward(*input, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/auc7us/Documents/Ultra-Fast-Lane-Detection-v2/deploy/../model/model_curvelanes.py", line 60, in forward
    lane_token = self.cls_distribute(fea).reshape(-1, 20, 1, self.input_height//32, self.input_width//32)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: shape '[-1, 20, 1, 25, 50]' is invalid for input of size 10000
```

**Comment by PINTO0309** [comment]
The resources I used more than two years ago have already been deleted and are no longer available to me, and I no longer remember what I did back then.

**Comment by Auc7us** [comment]
Thanks for the quick reply.
