### ISSUE TITLE
Running inference using 

### ISSUE THREAD

**Issue by SukyoungCho** [PINTO0309/PINTO_model_zoo#45]
Hi, I tried to run inference using a few edge TPU models from your model zoo, and faced the following errors. I was wondering if you could share the code script you used to run inference on mobile devices. Otherwise, It would be appreciated if you could help me solve these errors. Thank you so much.

Running on Odroid with coral usb acceleartor, ubuntu 18.01
**Trying to detect person**

### Error1: `ssd_mobilenet_v2_mnasfpn_shared_box_predictor_320_coco_full_integer_quant_edgetpu.tflite``
```
Traceback (most recent call last):
  File "one_ch_pd_app.py", line 62, in <module>
    init_inference()
  File "/root/Detection/person_detection.py", line 115, in init_inference
    interpreter = common.make_interpreter(input_model)
  File "/root/Detection/common.py", line 28, in make_interpreter
    {'device': device[0]} if device else {})
  File "/usr/local/lib/python3.5/dist-packages/tflite_runtime/interpreter.py", line 204, in __init__
    model_path, self._custom_op_registerers))
ValueError: Found too many dimensions in the input array of operation 'reshape'.
```

### Error2: `yolov4_416_full_integer_quant_edgetpu.tflite`
```
Traceback (most recent call last):
  File "one_ch_pd_app.py", line 77, in <module>
    objs = run_inference(THRESHOLD, 10, frame) # threshold, top_k, frame
  File "/root/Detection/person_detection.py", line 126, in run_inference
    interpreter.invoke()
  File "/usr/local/lib/python3.5/dist-packages/tflite_runtime/interpreter.py", line 506, in invoke
    self._interpreter.Invoke()
  File "/usr/local/lib/python3.5/dist-packages/tflite_runtime/interpreter_wrapper.py", line 113, in Invoke
    return _interpreter_wrapper.InterpreterWrapper_Invoke(self)
RuntimeError: Only float32 and uint8 is supported currently, got INT8.Node number 404 (LEAKY_RELU) failed to invoke.
```

### Error3: `ssd_mobilenet_v2_oid_v4_300x300_full_integer_quant_edgetpu.tflite`
I could run the inference, but the bounding box was not shown on the screen. I think it could be because the id (class label) for person is different in "open image dataset" but not sure what is the class label for person here

### Error4: `ssdlite_mobilenet_v2_coco_300_full_integer_quant_edgetpu.tflite`

```
Traceback (most recent call last):
  File "one_ch_pd_app.py", line 77, in <module>
    objs = run_inference(THRESHOLD, 10, frame) # threshold, top_k, frame
  File "/root/Detection/person_detection.py", line 127, in run_inference
    objs = get_output(score_threshold=threshold, top_k=top_k)
  File "/root/Detection/person_detection.py", line 83, in get_output
    scores = common.output_tensor(interpreter, 2)
  File "/root/Detection/common.py", line 48, in output_tensor
    output_details = interpreter.get_output_details()[i]
IndexError: list index out of range
```

**Comment by PINTO0309** [comment]
Is it possible to share the program you used for testing? It's difficult to identify what the problem is based on the error message alone.
